"""The vectors two teams exchange before a counted match.

A commitment formula that differs from the opponent's by one byte does not
degrade play — it makes two honest peers produce a ``TAMPERED`` verdict on a
clean match, voided, zero for both sides, and looking exactly like cheating.
That failure cannot be found by playing; it can only be found by comparing
numbers beforehand.

So ``fixtures/commit_vectors.json`` is an artefact meant to leave this
repository. It is checked here for our own protection and shared with an
opponent for theirs.

**The expected digests were not produced by the code under test.** They come
from a standalone transcription of the rulebook's ``commit()`` (p. 37) that
imports neither agent — because a fixture generated by the implementation it
checks proves only that the implementation equals itself, which is true of any
implementation including a wrong one.
"""

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest

from thief_agent.domain.crypto import canonical, commit_of

VECTORS = json.loads((Path(__file__).parent / "fixtures" / "commit_vectors.json").read_text())
CASES: list[dict[str, Any]] = VECTORS["vectors"]


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
class TestOurCommitMatchesTheRulebooksNumbers:
    def test_the_digest_is_reproduced_exactly(self, case: dict[str, Any]) -> None:
        assert commit_of(case["record"], case["nonce"]) == case["commit"]

    def test_the_digest_is_a_sha256_hexdigest(self, case: dict[str, Any]) -> None:
        assert len(case["commit"]) == 64
        assert set(case["commit"]) <= set("0123456789abcdef")


class TestTheVectorsCoverTheWaysTwoPeersDiverge:
    def test_key_order_cannot_change_the_digest(self) -> None:
        """Two records with the same content and different key order."""
        minimal = next(c for c in CASES if c["name"] == "minimal")
        reordered = next(c for c in CASES if c["name"] == "key_order_irrelevant")
        # dict equality ignores order, so compare the key sequence the file records
        assert list(minimal["record"]) != list(reordered["record"])
        assert minimal["record"] == reordered["record"]
        assert minimal["commit"] == reordered["commit"]

    def test_a_non_ascii_hint_is_covered(self) -> None:
        """The ``ensure_ascii`` question, where two honest peers disagree or nowhere.

        Hints are free natural language, so this is the vector most likely to
        be the one that fails against a real opponent.
        """
        case = next(c for c in CASES if c["name"] == "non_ascii_hint")
        assert not case["record"]["hint"].isascii()
        assert canonical(case["record"]).isascii()

    def test_a_barrier_placement_is_covered(self) -> None:
        """A position has to serialise the same way on both sides."""
        case = next(c for c in CASES if c["name"] == "barrier_placed")
        assert case["record"]["barrier_placed"] == [2, 2]

    def test_every_vector_says_what_it_is_for(self) -> None:
        """The file is read by another team; a vector with no reason is noise."""
        assert all(c["why"] and c["name"] for c in CASES)


class TestTheFixtureIsIndependentOfUs:
    def test_the_digests_come_from_the_rulebooks_formula_not_from_our_module(self) -> None:
        """Recomputed here from the literal p.37 construction.

        If our ``commit_of`` and this line ever disagree, the fixture is what
        is right — it is what the opponent will be running.
        """
        for case in CASES:
            payload = json.dumps(
                {**case["record"], "nonce": case["nonce"]},
                sort_keys=True,
                separators=(",", ":"),
            )
            assert hashlib.sha256(payload.encode("utf-8")).hexdigest() == case["commit"]

    def test_the_file_records_its_own_provenance(self) -> None:
        """So the next reader knows the numbers were not self-generated."""
        assert "importing neither agent" in VECTORS["generated_by"]
        assert "p. 37" in VECTORS["source"]

    def test_it_says_what_it_is_for(self) -> None:
        assert "before a counted match" in VECTORS["purpose"]


class TestTheTwoRepositoriesShareTheseVectors:
    def test_the_sibling_fixture_is_byte_identical(self) -> None:
        """Both agents must hash the same way as each other, not merely as the book.

        The pair is checked against a real opponent as one team, and a
        divergence between our own two agents would be found in a counted
        match rather than here.
        """
        sibling = Path(__file__).parents[3] / "police_agent" / "tests" / "fixtures"
        theirs = sibling / "commit_vectors.json"
        if not theirs.exists():  # pragma: no cover - only when checked out alone
            pytest.skip("sibling repository not checked out beside this one")
        ours = Path(__file__).parent / "fixtures" / "commit_vectors.json"
        assert theirs.read_bytes() == ours.read_bytes()


class TestTheCohortDisagreesWithItsOwnBook:
    """The reference implementation and the PDF compute different digests.

    Discovered by diffing against ``rmisegal/Game-P2P-Cop-Chase`` rather than
    by reasoning: the book's ``commit()`` (p. 37) folds the nonce into the
    record and leaves ``ensure_ascii`` at its default; the reference appends it
    after a pipe with ``ensure_ascii=False``. The book's precedence rule says
    the PDF wins, so that is what we send — but an opponent running the
    reference is honest, and refusing its commitments would be an unappealable
    rule 19 verdict against a clean match.
    """

    RECORD = {"step": 4, "move": "N", "intent": "truth", "hint": "past the harbour"}
    NONCE = "0123456789abcdef0123456789abcdef"

    def test_the_two_conventions_really_do_differ(self) -> None:
        from thief_agent.domain.crypto import reference_commit_of

        assert commit_of(self.RECORD, self.NONCE) != reference_commit_of(self.RECORD, self.NONCE)

    def test_we_send_the_books_form(self) -> None:
        expected = hashlib.sha256(
            json.dumps(
                {**self.RECORD, "nonce": self.NONCE}, sort_keys=True, separators=(",", ":")
            ).encode("utf-8")
        ).hexdigest()
        assert commit_of(self.RECORD, self.NONCE) == expected

    def test_the_reference_form_matches_the_cohorts_code(self) -> None:
        from thief_agent.domain.crypto import reference_commit_of

        canonical_text = json.dumps(
            self.RECORD, sort_keys=True, ensure_ascii=False, separators=(",", ":")
        )
        expected = hashlib.sha256(f"{canonical_text}|{self.NONCE}".encode()).hexdigest()
        assert reference_commit_of(self.RECORD, self.NONCE) == expected

    def test_verify_accepts_an_honest_peer_running_either(self) -> None:
        from thief_agent.domain.crypto import reference_commit_of, verify

        verify(self.RECORD, self.NONCE, commit_of(self.RECORD, self.NONCE))
        verify(self.RECORD, self.NONCE, reference_commit_of(self.RECORD, self.NONCE))

    def test_verify_still_refuses_a_digest_neither_produces(self) -> None:
        from thief_agent.domain.crypto import CryptoError, verify

        with pytest.raises(CryptoError):
            verify(self.RECORD, self.NONCE, "f" * 64)

    def test_a_non_ascii_hint_is_where_they_diverge_in_practice(self) -> None:
        """Hints are free natural language, so this arrives eventually."""
        from thief_agent.domain.crypto import reference_commit_of

        hebrew = {**self.RECORD, "hint": "ליד הפארק"}
        assert commit_of(hebrew, self.NONCE) != reference_commit_of(hebrew, self.NONCE)
