"""Regenerate the golden outcome ledger.

    python -m sparring.tests.gen_golden

Same idiom as the kit's fixtures: generated, committed, and re-generated in CI with
``git diff --exit-code`` after it — so a behavioural change has to be an intentional commit rather
than something that quietly happens.

The ledger, not the transcript, is what gets pinned: per sub-game the role, outcome, steps, scores
and final commit. That is stable against cosmetic changes and still fails the moment a policy, the
physics or the sealing changes what actually happened.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from sparring.config import SparConfig
from sparring.deadlines import FakeClock
from sparring.series import run_series

SEED = 1234
POLICIES = ("greedy", "random")
OUT = Path(__file__).resolve().parent / "golden" / "selfplay.json"


def main() -> None:
    ledgers = {}
    for policy in POLICIES:
        with tempfile.TemporaryDirectory() as td:
            result = run_series(SparConfig(seed=SEED, policy=policy), Path(td),
                                clock=FakeClock(), check_vectors=False)
        ledgers[policy] = result.ledger

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "_remark": "Generated by sparring/tests/gen_golden.py — do not edit. Regenerate and "
                   "commit when a behavioural change is intended; CI fails on undeclared drift.",
        "seed": SEED,
        "ledgers": ledgers,
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parents[3])}")


if __name__ == "__main__":
    main()
