"""Regenerate ``docs/EVIDENCE.md`` from a real sparring run — stdlib only.

    python gen_evidence.py

Same idiom as ``gen_vectors.py``: generated, committed, and regenerated in CI with
``git diff --exit-code`` after it, so the page cannot drift from the code that produced it.

**Why the bytes come from our own peer rather than from a real match.** Every frame below is
produced here, now, by ``sparring/`` playing itself — public code, public policies, nothing
strategic, nothing belonging to another team. A page of *real* cross-team frames would be a
disclosure judgment on every excerpt, could not be regenerated, and would publish an opponent's
play. This way the shapes are exact and the provenance is trivial.

What that costs, said plainly: these frames prove the *shape* of the protocol, not that two
independent implementations agreed on it. The evidence for **that** is the vectors (which a second
team reproduced byte-for-byte, see `docs/GOVERNANCE.md`) and the cross-team run cited there.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

import verify_vectors as ref
from sparring.config import SparConfig
from sparring.deadlines import FakeClock
from sparring.identity import locks
from sparring.negotiate import our_greeting
from sparring.series import run_series

OUT = Path(__file__).parent / "docs" / "EVIDENCE.md"
SEED = 4242


def _fence(obj, lang: str = "json") -> str:
    return f"```{lang}\n{json.dumps(obj, indent=2, ensure_ascii=False)}\n```"


def _trim(doc: dict, keep: tuple[str, ...]) -> dict:
    return {k: v for k, v in doc.items() if k in keep}


def main() -> None:
    cfg = SparConfig(seed=SEED, policy="random", hint_lang="mixed")

    with tempfile.TemporaryDirectory() as td:
        result = run_series(cfg, Path(td), clock=FakeClock(), check_vectors=False)
        run_dir = next(Path(td).iterdir())
        artifacts = {p.name: json.loads(p.read_text(encoding="utf-8"))
                     for p in sorted(run_dir.glob("*.json"))}
        log = artifacts[f"log_{result.game_id}_g01.json"]

    greeting = our_greeting(cfg, "police", 1, "0" * 32, locks(cfg.scent_model)).to_wire()
    step_zero = log["records"][0]
    game_step = next(r for r in log["records"] if r["payload"].get("step") == 2)

    # Two different non-ASCII hazards, which fail in different ways and are worth showing apart:
    # Hebrew is ordinary BMP text that a `\uXXXX`-escaping serializer mangles, and an astral-plane
    # emoji additionally exercises surrogate pairs. The peer only speaks each in some sub-games,
    # so both are searched for across the whole series rather than in the first log.
    def _find(predicate):
        for name in sorted(artifacts):
            if not name.startswith("log_"):
                continue
            found = next((r for r in artifacts[name]["records"]
                          if predicate(str(r["payload"].get("hint", "")))), None)
            if found is not None:
                return found
        return None

    hebrew = _find(lambda h: any(0x590 <= ord(c) <= 0x5FF for c in h))
    astral = _find(lambda h: any(ord(c) > 0xFFFF for c in h))

    lines = [
        "# Evidence — the wire, and the four artifacts",
        "",
        "**Generated by `gen_evidence.py` — do not edit.** Every frame below was produced by",
        "[`sparring/`](../sparring/) playing a real series, and CI regenerates this page and fails",
        "on any drift. So the shapes here are exactly what the code emits, not what someone",
        "remembered it emitting.",
        "",
        "> **What this page proves, and what it does not.** These are real frames from a real",
        "> implementation, so the *shapes* are exact. They do not prove that two independent",
        "> implementations agreed on them — that is what the vectors are for, and one of them was",
        "> reproduced byte-for-byte by a second team's clean-room build. See",
        "> [`GOVERNANCE.md`](GOVERNANCE.md) for what has actually been reproduced and by whom.",
        "",
        "Nothing here belongs to another team. The peer that produced it ships in this repo, its",
        "policies are public, and it has no mail surface at all.",
        "",
        "---",
        "",
        "## 1. The handshake",
        "",
        "The pre-game gate. `terms` is the flat signed set — the pairing fields and the",
        "locked-model hashes ride **beside** it, never inside, because adding a key to `terms`",
        "breaks the signature (SPEC §4, §7, §7.2).",
        "",
        _fence(greeting),
        "",
        f"The signature verifies as `SHA256(canonical_json(terms)|nonce)`, and both peers derive",
        f"the same ids from the signed terms plus the two group ids, with no round-trip:",
        "",
        "```",
        f"game_id  = {result.game_id}",
        f"game_uid = {result.game_uid}",
        "```",
        "",
        "`game_id` is the **sorted** pair. A peer that names itself first gives one match two",
        "different ids — see [`WARNINGS.md`](WARNINGS.md) §4.",
        "",
        "## 2. A sealed step-0 declaration",
        "",
        "Before the first move each side seals its hardware, model and code version (book ch.5,",
        "App. E rules 24 and 53). Only the `commit` crosses the wire; the `nonce` is withheld",
        "until the end-of-game audit.",
        "",
        _fence(step_zero),
        "",
        "## 3. A turn",
        "",
        "One half-turn. The move is **sealed, not sent** — the opponent gets a commit, a verbal",
        "hint that may lie, and the scent field, which cannot.",
        "",
        _fence(game_step),
        "",
        "The `intent` field is the declared truthfulness of the hint. Bluffing is legal; a bluff",
        "recorded as truth is tampering, because the opponent re-hashes this record at the audit.",
        "",
    ]

    if hebrew is not None or astral is not None:
        lines += [
            "### Why non-ASCII hints are in here on purpose",
            "",
            "The single most important fact in this kit is `ensure_ascii=False` (SPEC §2). A",
            "serializer that escapes non-ASCII produces a hint the opponent cannot re-hash, the",
            "audit reads it as tampering, and **both** teams score zero. So the sparring peer puts",
            "non-ASCII on the wire deliberately — a rehearsal that never leaves ASCII would let you",
            "discover this at a real opponent's audit instead.",
            "",
            "Two hazards, which fail differently and are worth testing separately.",
            "",
        ]
    if hebrew is not None:
        lines += [
            "**Ordinary non-ASCII text** — a `\\uXXXX`-escaping serializer changes every byte of it:",
            "",
            _fence(hebrew),
            "",
            "The canonical form of that payload hashes to:",
            "",
            "```",
            ref.canonical_hash(hebrew["payload"]),
            "```",
            "",
        ]
    if astral is not None:
        lines += [
            "**An astral-plane character**, which additionally exercises surrogate pairs — the",
            "case a language whose strings are UTF-16 is most likely to get wrong:",
            "",
            _fence(astral),
            "",
            "```",
            ref.canonical_hash(astral["payload"]),
            "```",
            "",
            "If your implementation reproduces both hashes above from the payloads shown, your",
            "serializer will survive an opponent's audit. If it does not, you have just found the",
            "single most expensive bug in this game, on your own schedule.",
            "",
        ]

    lines += [
        "## 4. The audit exchange",
        "",
        "At the end of a sub-game each side reveals every record with its nonce, and **the",
        "opponent** re-hashes them with its own serializer. Any mismatch is tampering by",
        "definition, and the sanction is total regardless of what happened on the board.",
        "",
        _fence({"sender": log["summary"]["role"],
                "result_claim": log["summary"]["result"],
                "records": ["… every record, each with its payload, nonce and commit …"],
                "_note": "the full reveal is the `records` array of the log artifact below"}),
        "",
        "The verdict this run produced, from the log artifact:",
        "",
        _fence(log["summary"]["audit"]),
        "",
        "## 5. The four artifacts",
        "",
        "Named by the book's App. F table 20 grammar, sharing **one `game_uid`** — the only key",
        "that joins a report to its own sealed logs and to the opponent's report.",
        "",
        "```",
        *[f"{name}" for name in sorted(artifacts)],
        "```",
        "",
        "### declaration",
        "",
        _fence(_trim(artifacts[f"declaration_{result.game_id}.json"],
                     ("schema_version", "declaration_type", "game_id", "game_uid",
                      "num_sub_games", "league", "mail_surface"))),
        "",
        "Two things worth noticing. `league.counted` is `false` and cites the rule that permits",
        "uncounted warm-ups — a practice artifact should never be mistakable for a league result.",
        "And `mail_surface` carries the hash of the scan proving the peer that wrote this file had",
        "no mail code in it: the artifact carries its own evidence.",
        "",
        "### result",
        "",
        _fence(_trim(artifacts[f"result_{result.game_id}.json"],
                     ("report_type", "game_id", "game_uid", "num_sub_games", "final_result",
                      "settlement", "league"))),
        "",
        "**There is no consensus signature in it, and that is deliberate.** A sparring run owes no",
        "report (App. E rule 52), so the result carries `settlement: not_owed` and nothing that",
        "could be verified — a label can be edited, but a missing preimage cannot be emailed.",
        "A counted run's result is where the signature belongs (SPEC §6).",
        "",
        "### log (one sub-game, summary only)",
        "",
        _fence(log["summary"]),
    ]

    # --- the one real cross-team frame -----------------------------------------------------
    frame_path = Path(__file__).parent / "docs" / "cross-team-frame.json"
    if frame_path.is_file():
        frame = json.loads(frame_path.read_text(encoding="utf-8"))
        greeting_in = frame["greeting"]
        # The claim "the same 14 keys this kit pins" is checked here rather than asserted: if the
        # signed set ever changes, generating this page fails instead of publishing a stale claim.
        pinned = set(json.loads((Path(__file__).parent / "vectors" / "terms_signature.json")
                                .read_text(encoding="utf-8"))["vectors"][0]["terms"])
        assert set(greeting_in["terms"]) == pinned, "their terms are not the 14-key set we pin"

        lines += [
            "",
            "---",
            "",
            "## 6. One real frame from another team",
            "",
            "Everything above came from our own peer. This did not: it is a genuine inbound",
            "greeting from **another team's independent implementation**, captured during the",
            "first fully autonomous cross-team series (2026-07-25 — six sub-games, one wire",
            "`game_uid`, mutual audits clean both ways).",
            "",
            "It is here because it shows the one thing generated bytes cannot: that a second",
            "implementation, built separately, put these fields on this wire — and that two of the",
            "hashes it declared are **byte-identical to this kit's registered documents**.",
            "",
            "> **Redaction is marked, never silent.** Every key the wire carried is present below;",
            "> five *values* are replaced, each saying what was removed. A dropped field would be a",
            "> claim about the protocol — and a false one, since a reader would conclude a",
            "> conforming greeting does not carry it.",
            "",
            _fence(greeting_in),
            "",
            "What to notice:",
            "",
            "- `role` and `sub_game_number` ride **beside** `terms`, not inside it (SPEC §7.2) —",
            "  the signed set is flat and closed, so a key added there breaks the signature.",
            f"- `scent_model_sha256` is `{greeting_in['scent_model_sha256'][:16]}…`, which equals",
            "  this kit's registered `multiplicative_book_v1`; `wire_shape_sha256` equals its",
            "  registered `reference-v3`. Two teams hashing the *same described model* to the",
            "  *same digest* is the entire point of pinning the document schema (SPEC §7) — a bare",
            "  hash over an ad-hoc dict would have differed while describing the same thing.",
            "- `hardware_spec_sha256` is a **fourth family this kit does not register**. It is not",
            "  added on the strength of one observation: the document underneath it is unknown to",
            "  us, and registering a family whose field set we have never seen would reintroduce",
            "  exactly the problem §7 removes.",
            "- `info_mode` travelled as a bare string, not a document hash — so that registration",
            "  is *not* reproduced by this frame. Only the intent was.",
            "",
            "And the settlement, from the same sub-game — their claim, and our verdict on their",
            "revealed records:",
            "",
            _fence({"their_claim": frame["audit_claim"],
                    "our_audit_of_their_records": frame["our_verdict_on_their_records"]}),
            "",
            "*Published with the other team's agreement, at interop level only. Nothing of how",
            "either side plays appears here or anywhere in this repository: no moves, no hints, no",
            "positions, no decisions — the failure ledger in* [`LEAGUE-OPS.md`](LEAGUE-OPS.md)",
            "*is anonymised for the same reason.*",
            "",
        ]

    lines += [
        "",
        "---",
        "",
        "## Reproducing this",
        "",
        "```bash",
        "python gen_evidence.py          # regenerates this page from a fresh run",
        f"python -m sparring.cli selfplay --seed {SEED} --policy random",
        "python tools/check_artifacts.py runs/sparring_*",
        "python -m sparring.cli replay   runs/sparring_*",
        "```",
        "",
        "The run is seeded, so the frames above are reproducible on your machine. If they are not,",
        "your Python disagrees with the pinned canonical form somewhere — which is exactly the",
        "thing worth finding now rather than during a match.",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(Path(__file__).parent)}")


if __name__ == "__main__":
    main()
