"""Regenerate every fixture under ``vectors/`` from the reference constructions in
``verify_vectors.py``. CI runs this and fails on any drift (the committed vectors must equal a
fresh regeneration). Inputs here are synthetic — our own values, not the reference simulator's
content — so the fixtures pin the *algorithms*, not anyone's copyrighted data.

Run: ``python gen_vectors.py`` then ``python verify_vectors.py``.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import verify_vectors as ref

VECTORS = Path(__file__).parent / "vectors"


# --- fixture tier registry ----------------------------------------------------------------
#
# Each fixture's tier is declared HERE, once. ``_write`` stamps it into the fixture as
# ``status``, and ``verify_vectors.py`` reads it back for the runtime banner — so a tier is
# never typed in two places and cannot drift. It did drift: ``multiplicative_book_v1`` was
# promoted on 2026-07-20 in the fixture while this file and the checker went on printing
# PROPOSED until 2026-07-26. What the tiers mean, and what promoting one requires, is in
# docs/GOVERNANCE.md.

TIERS: dict[str, tuple[str, str, str]] = {
    # fixture                    tier        SPEC     what it pins
    "canonical_json.json":      ("CORE", "§2", "the one canonical serialization under every hash"),
    "commit_reveal.json":       ("CORE", "§3", "the per-step commit, plus the release's three "
                                               "divergent constructions"),
    "terms_signature.json":     ("CORE", "§4", "the pre-game agreement signature"),
    "game_uid.json":            ("CORE", "§4", "the shared match id both peers derive without a "
                                               "round-trip"),
    "pheromone.json":           ("CORE", "§5", "`subtractive_chebyshev_v1` emission and decay"),
    "report_consensus.json":    ("CORE", "§6", "the settlement signature's second (spaced) form, "
                                               "sign-then-insert"),
    "locked_model.json":        ("CORE", "§7", "the locked-model doc schema and the refusal truth "
                                               "table"),
    "pairing_declaration.json": ("PROMOTED", "§7.2", "`sub_game_number` + `role` in the negotiate "
                                                     "extras, and when they refuse"),
    "delivery_contract.json": ("PROMOTED", "§7.1", "the at-least-once receiver contract, as a "
                                                   "decision table"),
    "turn_message.json":      ("PROMOTED", "§7.5", "the reference-v3 wire surface: what each "
                                                   "tool carries, and what refuses"),
    "uid_declaration.json":   ("PROPOSED", "§7.3", "declaring the derived `game_uid` at "
                                                   "negotiate, and when it refuses"),
    "smell_binding.json":     ("PROPOSED", "§7.4", "binding the transmitted smell grid into the "
                                                   "sealed step record"),
    "scent_book_v3.json":   ("PROMOTED", "§5.1", "`multiplicative_book_v1` — the book's own scent "
                                                 "model"),
    "joint_seed.json":           ("ENH", "App. A", "the joint-seed coin flip (opt-in)"),
    "derive_starts.json":        ("ENH", "App. A", "seeded asymmetric starts (opt-in)"),
}


def _write(name: str, obj: dict) -> None:
    if name not in TIERS:
        raise SystemExit(
            f"{name}: no tier registered. Add it to TIERS above — a fixture whose tier is not "
            f"declared cannot state its own status, and the checker will refuse it. "
            f"See docs/GOVERNANCE.md."
        )
    tier = TIERS[name][0]
    # `status` sits right after `description` in every fixture, stamped from the registry rather
    # than written by hand in the generator body.
    stamped: dict = {}
    if "description" in obj:
        stamped["description"] = obj["description"]
    stamped["status"] = tier
    stamped.update({k: v for k, v in obj.items() if k not in ("description", "status")})
    text = json.dumps(stamped, indent=2, ensure_ascii=False) + "\n"
    (VECTORS / name).write_text(text, encoding="utf-8")
    print(f"wrote {name}  [{tier}]")


def gen_index() -> None:
    """Write ``vectors/INDEX.md`` — the fixture roster, generated so it cannot drift.

    Prose elsewhere links here instead of restating counts; CI's ``git diff --exit-code``
    then makes the roster a checked claim rather than a maintained one.
    """
    rows = [f"| [`{n}`]({n}) | `{t}` | {s} | {w} |" for n, (t, s, w) in TIERS.items()]
    text = "\n".join([
        "# Fixture index",
        "",
        "**Generated by `gen_vectors.py` — do not edit.** Each fixture declares its own `status`;",
        "`verify_vectors.py` reads it back, so a tier is stated once and cannot go stale.",
        "",
        "What the tiers mean and what promoting one requires:",
        "[`../docs/GOVERNANCE.md`](../docs/GOVERNANCE.md).",
        "For the current check count, run `python verify_vectors.py` — it prints the roster and",
        "the totals it actually ran.",
        "",
        "| Fixture | Tier | SPEC | What it pins |",
        "|---|---|---|---|",
        *rows,
        "",
    ])
    (VECTORS / "INDEX.md").write_text(text, encoding="utf-8")
    print("wrote INDEX.md")


# --- CORE -------------------------------------------------------------------------------

def gen_canonical_json() -> None:
    objects = [
        ({"b": 1, "a": {"d": 4, "c": 3}}, "sorted keys, nested object"),
        ({"hint": "אני ליד הכיכר", "move": "MOVE:N"}, "Hebrew hint stays native UTF-8 (ensure_ascii=False)"),
        ({"emoji": "🙂", "x": 1}, "astral emoji stays native — NOT \\uXXXX surrogate-escaped"),
        ({"decay_per_step": 0.1, "emit_intensity": 0.9, "min_center_intensity": 0.5,
          "ram_gb": 31.8, "vram_gb": 6.0}, "floats permitted; must be shortest round-trip repr"),
        ({"a": True, "b": None, "c": [1, 2, 3]}, "JSON literals + int array"),
        # The two cases below close gaps anrbj666's 2026-08-04 audit found: every earlier case
        # had ASCII (or BMP-only) KEYS, so key-sort order was never exercised where languages
        # disagree — and no float ever reached an exponent representation.
        ({"🙂": "astral key", "～": "high-BMP key"},
         "KEY SORT is by Unicode CODE POINT: U+FF5E sorts before U+1F642. A UTF-16 code-unit "
         "sort (JS Object.keys().sort(), Java, C#) orders these two the OTHER way — surrogate "
         "0xD83D < 0xFF5E — so a team on such a runtime must sort by code point explicitly "
         "(found by anrbj666)"),
        ({"tiny": 1e-07, "huge": 1e16},
         "float repr at the exponent cliff is PYTHON'S shortest-repr, exactly: '1e-07' (not "
         "'1e-7') and '1e+16' (not '10000000000000000'). Other languages' shortest-repr rules "
         "differ here; game values never reach these magnitudes, but the canonical form is "
         "pinned to these bytes regardless (found by anrbj666)"),
    ]
    _write("canonical_json.json", {
        "description": "The one canonical form every hash uses: json.dumps(obj, sort_keys=True, "
                       "ensure_ascii=False, separators=(',', ':')), UTF-8. ensure_ascii=FALSE is "
                       "the load-bearing detail — see SPEC section 'Canonical JSON'.",
        "serialization": {"sort_keys": True, "ensure_ascii": False, "separators": [",", ":"]},
        "vectors": [
            {"object": o, "note": note, "canonical": ref._canonical_str(o), "sha256": ref.canonical_hash(o)}
            for o, note in objects
        ],
    })


def gen_commit_reveal() -> None:
    cases = [
        ({"step": 0, "type": "system_spec", "spec": {"os": "Linux", "cpu_cores": 4,
          "ram_gb": 16.0, "vram_gb": 0.0}, "model": "cli-default", "code_version": "1.0",
          "group_name": "Example-Team", "sub_game_number": 1},
         "0f1e2d3c4b5a69788796a5b4c3d2e1f0", "step-0 host-spec record (floats in spec)"),
        ({"step": 1, "state": "grid=7x7;self=[4, 3];barriers=[]", "position": [4, 3],
          "move": "MOVE:S", "intent": "truth", "hint": "I keep to the main avenues."},
         "112233445566778899aabbccddeeff00", "move record, ASCII hint"),
        ({"step": 2, "state": "grid=7x7;self=[2, 4];barriers=[[1, 1]]", "position": [2, 4],
          "move": "MOVE:N", "intent": "lie", "hint": "אני ליד הכיכר 🙂"},
         "deadbeefcafef00dfeedface00c0ffee",
         "non-ASCII hint — pins ensure_ascii=False; escaping here => opponent's audit re-hash "
         "mismatches => false tamper_forfeit => both score 0"),
    ]
    # The v3.0.0 release publishes three inconsistent commit constructions (book ch.5 listing:
    # nonce inside the object; book audit snippet: f"{nonce}|{move}"; reference code:
    # canonical|nonce). The kit pins the reference form; this entry hashes ONE identical input
    # under all three so a failing team can identify which form it accidentally implemented.
    div_payload, div_nonce = cases[1][0], cases[1][1]
    divergent = {
        "payload": div_payload,
        "nonce": div_nonce,
        "reference_form": ref.ref_commit(div_payload, div_nonce),
        "book_ch5_listing_form": ref.canonical_hash({**div_payload, "nonce": div_nonce}),
        "book_audit_snippet_form": hashlib.sha256(
            f"{div_nonce}|{div_payload['move']}".encode()
        ).hexdigest(),
        "note": "The same sealed record under the release's three published constructions — all "
                "three hashes differ. reference_form and book_ch5_listing_form hash the full "
                "record; book_audit_snippet_form structurally consumes only nonce|move, so it "
                "binds neither state nor intent (position/bluff tampering would go undetected). "
                "Only reference_form is this kit's CORE form (SPEC 'Commit-reveal'). If your "
                "commits equal one of the other two, you implemented from one of the book's "
                "illustrative listings — switch to the reference form.",
    }
    _write("commit_reveal.json", {
        "description": "Per-step commit-reveal seal. commit = SHA256(canonical_json(payload)|nonce). "
                       "Self-sealed by each peer; re-hashed by the OPPONENT at audit — so the "
                       "canonical form must match cross-team even though the payload does not.",
        "construction": "sha256(utf8(canonical_json(payload) + '|' + nonce))",
        "vectors": [
            {"payload": p, "nonce": n, "note": note, "commit": ref.ref_commit(p, n)}
            for p, n, note in cases
        ],
        "divergent_forms": divergent,
    })


def gen_terms_signature() -> None:
    terms = {
        "board_size": 7, "smell_grid_size": 5, "decay_per_step": 0.1, "emit_intensity": 0.9,
        "min_center_intensity": 0.5, "max_steps": 35, "barriers_max": 14, "setting": "Haifa",
        "hint_max_words": 15, "axis_origin_corner": "top-left", "axis_start_index": 0,
        "thief_start": [3, 3], "cop_start": [0, 0], "num_games": 1,
    }
    nonce = "a1a2a3a4b1b2b3b4c1c2c3c4d1d2d3d4"
    _write("terms_signature.json", {
        "description": "Pre-game agreement gate. signature = SHA256(canonical_json(terms)|nonce), "
                       "the same construction as a commit, over the agreed terms. The opponent "
                       "re-verifies over the terms it received (which must value-equal its own). "
                       "The float 0.1 pins shortest round-trip repr — a language that emits "
                       "'0.10000000000000001' fails the signature and cannot play.",
        "vectors": [{"terms": terms, "nonce": nonce, "signature": ref.ref_terms_signature(terms, nonce)}],
    })


def gen_game_uid() -> None:
    # The FULL 14-key flat signed set. An earlier revision of this fixture used a 12-key dict
    # (no axis_origin_corner / axis_start_index) — and a team treating that worked example as
    # "the flat terms" would reproduce exactly the wrong-input uid failure this kit warns about
    # (WARNINGS section 2). Found by anrbj666's 2026-08-04 audit.
    terms = {"board_size": 7, "smell_grid_size": 5, "decay_per_step": 0.1, "emit_intensity": 0.9,
             "min_center_intensity": 0.5, "max_steps": 35, "barriers_max": 14, "setting": "Haifa",
             "hint_max_words": 15, "axis_origin_corner": "top-left", "axis_start_index": 0,
             "thief_start": [3, 3], "cop_start": [0, 0], "num_games": 1}
    a, b = "team-aleph", "team-bet"
    _write("game_uid.json", {
        "description": "The two deterministic match ids both peers reproduce with no round-trip. "
                       "game_uid = UUID(SHA256(canonical(terms)|'|'.join(sorted([g_a,g_b])))[:16]) "
                       "names the match cryptographically; game_id = '-vs-'.join(sorted([g_a,g_b])) "
                       "names its four artifact files. BOTH sort the pair, so group order does not "
                       "matter and neither side has to be told which name to use. A peer that "
                       "names itself first produces a different game_id on each side, and one "
                       "match then yields two sets of filenames that cannot be joined.",
        "vectors": [
            {"terms": terms, "group_a": a, "group_b": b, "game_uid": ref.ref_game_uid(terms, a, b),
             "game_id": ref.ref_game_id(a, b), "note": "canonical order"},
            {"terms": terms, "group_a": b, "group_b": a, "game_uid": ref.ref_game_uid(terms, b, a),
             "game_id": ref.ref_game_id(b, a),
             "note": "groups swapped -> identical uid AND identical game_id (both sorted)"},
        ],
        "artifact_filenames": {
            "note": "the book's App. F table 20 grammar, derived from the game_id above. "
                    "Per-sub-game files carry a zero-padded _g<NN>; all four carry the same "
                    "game_uid inside, which is what joins them to the sealed logs.",
            "declaration": f"declaration_{ref.ref_game_id(a, b)}.json",
            "config": f"config_{ref.ref_game_id(a, b)}_g<NN>.json",
            "log": f"log_{ref.ref_game_id(a, b)}_g<NN>.json",
            "result": f"result_{ref.ref_game_id(a, b)}.json",
        },
    })


def gen_pheromone() -> None:
    emit = [
        {"center": [3, 3], "intensity": 0.9, "grid_size": 5, "board_size": 7,
         "note": "full 5x5 field, centre 0.9, falloff 0.3/step"},
        {"center": [0, 0], "intensity": 0.9, "grid_size": 5, "board_size": 7,
         "note": "corner emission clipped to board bounds"},
    ]
    for e in emit:
        e["field"] = ref.ref_smell_emit(e["center"], e["intensity"], e["grid_size"], e["board_size"])
    decay = [
        {"before": {"3,3": 0.9, "3,4": 0.6, "3,5": 0.3}, "decay": 0.1,
         "note": "one step of decay by 0.1"},
        {"before": {"1,1": 0.05}, "decay": 0.1, "note": "clamps to 0.0 at the floor"},
    ]
    for d in decay:
        d["after"] = ref.ref_smell_decay(d["before"], d["decay"])
    _write("pheromone.json", {
        "description": "Scent field (book ch.4). Radial emit: half=grid//2, falloff=intensity/"
                       "(half+1), value=round(max(0,intensity-falloff*chebyshev),3). Decay/step: "
                       "round(max(0,v-decay),3). Only value>0 crosses the wire as {'r,c': value}. "
                       "Each peer emits its own and transmits it, so this is a self-test — but a "
                       "correct port is what makes your belief map behave as the book describes.",
        "emit": emit, "decay": decay,
    })


def gen_report_consensus() -> None:
    sig_key = "חתימת_קונסנזוס_משותפת"
    reports = [
        ({"קבוצה_א": "team-aleph", "קבוצה_ב": "team-bet",
          "תוצאה": {"מנצחת": "team-aleph", "ניקוד": [20, 5]},
          "game_uid": "f757f50d-d4f4-17e7-06cf-755905739b16",
          "tokens_total_series": 0, "github_commit": "abc1234"},
         "Hebrew-keyed report body (floats absent)"),
        ({"סדרה": [{"משחקון": 1, "ניקוד": [5, 10]}, {"משחקון": 2, "ניקוד": [20, 5]}],
          "ram_gb": 31.8, "decay_per_step": 0.1, "mutual_agreement": True},
         "nested list + floats — spaced form still shortest-round-trip floats"),
    ]
    vectors = []
    for report, note in reports:
        sig = ref.ref_report_consensus_signature(report)
        vectors.append({
            "report": report,
            "note": note,
            "signature": sig,
            "signed_report": {**report, sig_key: sig},
            "compact_form_sha256": ref.canonical_hash(report),
        })
    _write("report_consensus.json", {
        "description": "Settlement consensus signature — the release's SECOND canonical form "
                       "(reference report_writer.py, verified at sha 960499fd): "
                       "json.dumps(report, sort_keys=True, ensure_ascii=False) with DEFAULT "
                       "(spaced) separators, then SHA-256. The signature is computed BEFORE the "
                       "signature key is inserted (sign-then-insert) — verify by popping the key, "
                       "re-serializing spaced, re-hashing. compact_form_sha256 shows the §2 "
                       "compact form does NOT reproduce it: a team signing compact fails "
                       "settlement at the exact moment both teams must agree. Found by Alon's "
                       "team (alonengel / anrbj666).",
        "serialization": {"sort_keys": True, "ensure_ascii": False,
                          "separators": [", ", ": "], "separators_note": "json.dumps defaults"},
        "signature_key": sig_key,
        "vectors": vectors,
    })


# --- LOCKED-MODEL DECLARATIONS (SPEC section 7) -------------------------------------------
#
# Registered docs. Each is an input here, not an output: the fixture stores the doc AND its
# hash, and verify_vectors.py re-derives the hash from the stored doc.

BOOK_KERNEL_ROWS = [list(row) for row in ref.BOOK_KERNEL]


def _doc_scent_subtractive() -> dict:
    return ref.ref_lock_doc(
        "scent_model", "subtractive_chebyshev_v1",
        {
            "field_size": 5, "emit_intensity": 0.9, "min_center_intensity": 0.5,
            "distance": "chebyshev", "falloff": "linear",
            "falloff_step": "emit_intensity / (field_size // 2 + 1)",
            "decay": "subtractive", "decay_per_step": 0.1,
            "update": "tau' = round(max(0, tau - decay_per_step), 3)",
            "rounding_decimals": 3, "clamp": [0.0, None],
            "cadence": "per_full_turn", "order": "deposit_then_decay",
            "receiver_side_decay": True, "initial_field": "empty",
            "transmitted": True,
        },
        {
            "note": "emit at the centre of a 7x7 board, then one decay",
            "emit_center": [3, 3],
            "emit_field": ref.ref_smell_emit([3, 3], 0.9, 5, 7),
            "after_one_decay": ref.ref_smell_decay(ref.ref_smell_emit([3, 3], 0.9, 5, 7), 0.1),
        },
    )


def _doc_scent_book() -> dict:
    return ref.ref_lock_doc(
        "scent_model", "multiplicative_book_v1",
        {
            "field_size": 5, "center_intensity": 0.9, "decay_rho": 0.1,
            "kernel": BOOK_KERNEL_ROWS,
            "kernel_source": "book v3.0.0 figure 4 — printed values, verbatim lookup",
            "decay": "multiplicative",
            "update": "tau' = clamp((1 - rho) * tau + kernel_delta, 0, center_intensity)",
            "evaluation_order": "(1 - rho) * tau + delta, then clamp",
            "rounding_decimals": None, "clamp": [0.0, 0.9],
            "cadence": "per_full_turn", "order": "decay_then_deposit",
            "receiver_side_decay": False, "initial_field": "empty",
            "transmitted": False,
        },
        {
            "note": "the clamp case: a saturated cell decays, then takes an adjacent deposit",
            "tau": 0.9, "delta": 0.62,
            "raw": (1 - 0.1) * 0.9 + 0.62,
            "clamped": ref.ref_book_update(0.9, 0.62, 0.1, 0.9),
        },
    )


def _doc_wire_reference() -> dict:
    return ref.ref_lock_doc(
        "wire_shape", "reference-v3",
        {
            "tools": ["negotiate", "receive_turn", "submit_audit", "receive_control"],
            "messages_per_half_turn": 1,
            "smell_grid_on_wire": True,
            "move_revealed": "at_audit",
            "replicated_engines": False,
            "phases": "all four of book ch.5, with Reveal deferred to the audit boundary",
            "rival_position_computable_live": False,
        },
        {
            "note": "one turn message per half-turn; the move is sealed, the field is sent",
            "turn_message_keys": ["step", "commit", "hint", "smell_grid", "barrier_placed"],
        },
    )


def _doc_wire_bookletter() -> dict:
    return ref.ref_lock_doc(
        "wire_shape", "bookletter-v3",
        {
            "messages_per_half_turn": 2,
            "message_kinds": ["commit", "reveal"],
            "smell_grid_on_wire": False,
            "move_revealed": "per_half_turn",
            "replicated_engines": True,
            "commit_order": "police_first",
            "withheld_until_audit": ["nonce", "verdict"],
            "sealed_payload_fields": ["step", "role", "sub_game", "state_digest", "action",
                                      "hint", "verdict"],
            "audit_message_keys": ["end_state_digest", "group_id", "nonces", "verdicts"],
            "rival_position_computable_live": True,
            "unpinned_preimages": ["state_digest", "end_state_digest", "config_sha256",
                                   "terms_signature"],
        },
        {
            "note": "contributed by anrbj666 (Alon Engel, Renat Karimov), kit issue #6; the "
                    "commit layer reproduces under the section-3 construction over the full "
                    "7-field payload, the four preimages above are not yet pinned",
            "commit_construction": "SHA256(canonical(payload) + '|' + nonce)",
        },
    )


def _doc_info_mode(name: str, exact: bool) -> dict:
    return ref.ref_lock_doc(
        "info_mode", name,
        {
            "rival_position_in_observation": exact,
            "sources": (["own_state", "rival_position", "rival_scent", "hints"] if exact
                        else ["own_state", "rival_scent", "hints"]),
            "enforcement": ("structural under wire_shape reference-v3 (the rival's position "
                            "never crosses the wire); an honor term under bookletter-v3, where "
                            "the wire carries it and only the brain's restraint withholds it"),
            "artifact_provable": {
                "mismatch": True,
                "violation": False,
                "why": "a mismatch is provable from the two negotiate records; a violation is "
                       "not, because a decision record does not disclose which information "
                       "produced it",
            },
        },
        {
            "note": "the observation space the brain is entitled to read",
            "observation_keys": (["self", "barriers", "rival_position", "smell_grid", "hint"]
                                 if exact else ["self", "barriers", "smell_grid", "hint"]),
        },
    )


# The sample field the smell-binding registration and fixture both work from. Deliberately tiny
# and deliberately mixed-width: a board wider than ten produces the key `"10,1"`, which canonical
# JSON sorts BEFORE `"2,3"` because the keys are strings. Sorting a grid numerically before
# serializing is the one way two correct implementations disagree on this digest.
BINDING_SAMPLE_GRID = {"2,3": 0.9, "2,4": 0.6, "10,1": 0.3}


def _doc_smell_binding_none() -> dict:
    return ref.ref_lock_doc(
        "smell_binding", "none",
        {},
        {
            "note": "the default and the whole of today's wire: the transmitted grid is "
                    "unauthenticated. Registered so that `unbound` is a state a peer can "
                    "declare rather than a silence it cannot distinguish from ignorance.",
            "sealed_record_keys_added": [],
        },
    )


def _doc_smell_binding_commit_grid() -> dict:
    return ref.ref_lock_doc(
        "smell_binding", "commit_grid_v1",
        {
            "binds": "smell_grid",
            "sealed_record_key": "smell_grid_sha256",
            "digest": "sha256(canonical_json(smell_grid_as_transmitted))",
            "grid_as_transmitted": "the exact wire value of that step's smell_grid; an empty "
                                   "grid is {} and hashes as {}",
            "commit_construction": "unchanged — the key rides the existing section-3 preimage",
            "wire": "unchanged",
            "verified_at": "mutual_audit",
            "mismatch_grade": "audit",
            "buys": ["authenticity"],
            "does_not_buy": ["privacy"],
        },
        {
            "note": "the digest a sender seals for one step; the verifier re-hashes the grid it "
                    "archived as received and compares",
            "smell_grid": BINDING_SAMPLE_GRID,
            "smell_grid_sha256": ref.ref_smell_grid_sha256(BINDING_SAMPLE_GRID),
            "empty_grid_sha256": ref.ref_smell_grid_sha256({}),
        },
    )


def gen_locked_model() -> None:
    docs = [_doc_scent_subtractive(), _doc_scent_book(), _doc_wire_reference(),
            _doc_wire_bookletter(), _doc_info_mode("belief", exact=False),
            _doc_info_mode("exact", exact=True),
            _doc_smell_binding_none(), _doc_smell_binding_commit_grid()]
    # Per-registration status. A registration is not a fixture, so it carries its own tier here
    # rather than through TIERS; the rules in docs/GOVERNANCE.md are the same ones.
    status = {
        "subtractive_chebyshev_v1": ("CORE", "the reference implementation's own model; pinned "
                                             "byte-for-byte by pheromone.json (section 5)"),
        "multiplicative_book_v1": ("PROMOTED", "clean-room reproduction by anrbj666 (issue #6, "
                                               "2026-07-20), and this exact doc hash was declared "
                                               "on the wire by their peer throughout the "
                                               "2026-07-25 cross-team series"),
        "reference-v3": ("PROMOTED", "two independent implementations played a full six-sub-game "
                                     "cross-team series on this shape (2026-07-25), mutual audits "
                                     "clean both ways, and their peer declared this exact doc "
                                     "hash"),
        "bookletter-v3": ("PROPOSED", "one implementation; four preimages still unpinned, so the "
                                      "hash will change when they are settled"),
        "belief": ("PROMOTED", "declared as `info_mode_sha256` by BOTH independent "
                               "implementations, byte-identical to this registration, in every "
                               "handshake from the 2026-08-01 warm-up through the 2026-08-04 "
                               "counted series (both role directions) — see live_reproduction "
                               "below, where the checker asserts the observed hash still equals "
                               "the registered doc. On 2026-07-25 it had travelled as a bare "
                               "string; that limit is discharged"),
        "exact": ("PROPOSED", "registered as the counterpart of `belief`; no second "
                              "implementation has declared it"),
        "none": ("PROPOSED", "the unbound default. It describes what every implementation "
                             "already does, but NO implementation declares it yet — the "
                             "registration exists so that `unbound` becomes sayable"),
        "commit_grid_v1": ("PROPOSED", "agreed by both league teams on 2026-07-29 as worth "
                                       "doing on its own merits — proposed by anrbj666, scoped "
                                       "by imreeyal. NOT YET IMPLEMENTED BY ANYONE: this is the "
                                       "weakest form of PROPOSED, published so a first and a "
                                       "second implementation can both build to it. Promotion "
                                       "needs the usual two, plus a live warm-up — it changes a "
                                       "commit preimage, so it never debuts in a counted game"),
    }
    registered = [{"doc": d, "declared_as": f"{d['family']}_sha256",
                   "sha256": ref.ref_lock_hash(d),
                   "status": status[d["name"]][0], "evidence": status[d["name"]][1]}
                  for d in docs]
    by_name = {d["doc"]["name"]: d["sha256"] for d in registered}
    # The refusal rule is behavioural, not byte-level, so it gets its own truth table.
    a, b = by_name["subtractive_chebyshev_v1"], by_name["multiplicative_book_v1"]
    decisions = [
        (a, a, "both declare, same model"),
        (a, b, "both declare, different models"),
        (a, None, "we declare, they are silent (e.g. the unmodified reference peer)"),
        (None, b, "they declare, we are silent"),
        (None, None, "neither declares"),
    ]
    _write("locked_model.json", {
        "description": "Locked-model declarations — ONE doc schema serving FOUR named-parameter "
                       "families (scent_model, wire_shape, info_mode, smell_binding). A peer "
                       "publishes a doc, "
                       "hashes it with the section-2 compact canonical form, and declares only "
                       "the hash at negotiate time under '<family>_sha256'. The schema exists so "
                       "that two teams' hashes are COMPARABLE: a bare hash over an ad-hoc dict "
                       "makes two correct implementations of the same model refuse each other. "
                       "Refusal fires ONLY when both peers declare a family and disagree — "
                       "omission is never refusal. See SPEC section 7.",
        "doc_schema": {"keys": list(ref.LOCK_DOC_KEYS), "families": list(ref.LOCK_FAMILIES),
                       "hash": "sha256(canonical_json(doc))",
                       "declared_key": "<family>_sha256"},
        "registered": registered,
        "declaration_example": {
            "note": "what actually crosses the wire in the negotiate extras — hashes only",
            "scent_model_sha256": by_name["multiplicative_book_v1"],
            "wire_shape_sha256": by_name["reference-v3"],
            "info_mode_sha256": by_name["belief"],
        },
        "refusal_rule": [
            {"ours": o, "theirs": t, "note": note, "decision": ref.ref_lock_decision(o, t)}
            for o, t, note in decisions
        ],
        "live_reproduction": {
            "note": "the mechanism, exercised end-to-end by two independent implementations "
                    "(imreeyal / anrbj666) across two cited runs. Run 1, 2026-07-25: a full "
                    "six-sub-game cross-team series, mutual audits clean both ways; their "
                    "peer's inbound greeting declared the scent_model and wire_shape hashes "
                    "below, each byte-identical to this kit's registered doc — the whole claim "
                    "of this section, since a bare hash over an ad-hoc dict would have differed "
                    "while describing the same model. The mechanism also demonstrably REFUSED: "
                    "an earlier attempt that night aborted on a scent lock mismatch, before any "
                    "game was played. Run 2, the 2026-08-01..04 campaign (five friendly series "
                    "and the 2026-08-04 counted series): every handshake in both role "
                    "directions additionally declared info_mode_sha256, byte-identical to the "
                    "registered `belief` doc — on 2026-07-25 the mode had travelled as a bare "
                    "string, a limit discharged by run 2.",
            "observed_declarations_matching_registrations": {
                "scent_model_sha256": by_name["multiplicative_book_v1"],
                "wire_shape_sha256": by_name["reference-v3"],
                "info_mode_sha256": by_name["belief"],
            },
            "observed_but_not_registered_here": {
                "hardware_spec_sha256": "a FOURTH family observed on the wire that this kit does "
                                        "not register. It is not added here on the strength of "
                                        "one observation: the doc underneath it is unknown, and "
                                        "registering a family whose field set we have not seen "
                                        "would reintroduce exactly the ad-hoc-dict problem this "
                                        "section removes.",
            },
        },
    })


def gen_turn_message() -> None:
    """SPEC §7.5 — what the reference-v3 tools actually carry."""
    example = {
        "step": 7,
        "sender": "police",
        "hint": "north of the park",
        "smell_grid": {"3,3": 0.9, "3,4": 0.5, "4,3": 0.5},
        "commit": "a" * 64,
        "timestamp": "2026-08-08T19:00:00Z",
        "barrier_placed": [5, 6],
        "capture_claim": None,
        "claim_response": None,
        "win_claim": None,
    }
    cases = [
        (example, "the full ten-key set, nulls explicit"),
        ({**example, "unknown_field": {"anything": 1}},
         "an UNKNOWN key is tolerated and ignored — the extension seam. A receiver that "
         "refuses it cannot be extended without a flag day"),
        ({**example, "timestamp": ""},
         "empty timestamp REFUSED. Decorative field, load-bearing refusal: this kit's own "
         "sparring peer sends an empty string, so every one of its turns is rejected by a "
         "conformant receiver. A pair may agree to tolerate it — but BOTH must, because one "
         "side tolerating it plays a series the other refuses"),
        ({k: v for k, v in example.items() if k != "commit"},
         "a MISSING required key is refused, never defaulted — a defaulted commit is a move "
         "the sender never sealed"),
        ({**example, "commit": "A" * 64},
         "uppercase hex refused: the commit is compared as a string, so case is a divergence"),
        ({**example, "smell_grid": {"3,3": "0.9"}},
         "a stringified intensity refused — it survives JSON and poisons the physics check"),
        ({**example, "step": -1}, "a negative step is not a step"),
    ]
    _write("turn_message.json", {
        "description": "PROMOTED — the reference-v3 wire surface (SPEC §7.5). The tool "
                       "NAMES were already published inside the `wire_shape: reference-v3` locked "
                       "document; what was missing was the SHAPE of what they carry, so a team "
                       "could read the names and still have nothing to build against. best2934 "
                       "lost a scheduled friendly to that gap (issue #45): fourteen agreed terms, "
                       "verifying signatures, green tunnels both sides, and tool surfaces "
                       "disjoint except for `negotiate`. Promoted rather than proposed because "
                       "this surface has carried two full counted six-sub-game series over public "
                       "tunnels between independently written peers (imreeyal vs anrbj666 "
                       "2026-08-04; imreeyal vs uoh-sqak 2026-08-08), mutual audits clean both "
                       "ways.",
        "tools": {
            "negotiate": "REQUIRED. The pre-game gate: flat terms + nonce + signature + identity. "
                         "Either side may open. See §4.",
            "receive_turn": "REQUIRED. One TurnMessage, one message per half-turn. Each side "
                            "CALLS the other's receive_turn with its own turn — the transport "
                            "is symmetric push, so neither peer can be purely passive.",
            "submit_audit": "REQUIRED. One AuditPayload per sub-game: the full sealed chain plus "
                            "nonces, for the opponent to re-hash.",
            "receive_control": "OPTIONAL. A status channel that touches no game state and is "
                               "never sealed or scored. Answering 200 is conformant; omitting it "
                               "costs nothing.",
        },
        "not_on_this_wire": {
            "declare_step0": "there is no step-0 tool and no step-0 TURN. The hardware/model "
                             "declaration rides in `negotiate` under `identity`, and the sealed "
                             "step-0 record is disclosed inside `submit_audit` — never "
                             "transmitted as a turn. A peer that waits for a step-0 call waits "
                             "forever.",
            "hello": "not part of this surface. A liveness probe should be `tools/list`, not a "
                     "tool CALL: a peer implementing none of your names is still up, and "
                     "`negotiate` is the authority on whether you may play. Reading an "
                     "unknown-tool error as 'peer is down' is how best2934 spent five minutes "
                     "calling a live opponent absent (issue #45).",
        },
        "turn_message": {
            "required": list(ref.TURN_REQUIRED),
            "optional": list(ref.TURN_OPTIONAL),
            "field_notes": {
                "step": "each peer numbers its OWN chain 1..max_steps. A step is a ROUND (one "
                        "action from each side), NOT a half-turn — so `max_steps: 35` means "
                        "35 moves EACH. Two peers reading this differently agree on every term "
                        "and still desync, and no gate either side builds will catch it.",
                "sender": "'police' | 'thief'",
                "hint": "the <=15-word verbal hint; may be empty, and may be a lie (App. E "
                        "permits deception in the verbal channel)",
                "smell_grid": "{'r,c': intensity} — on the wire under reference-v3",
                "commit": "SHA256(canonical_json(payload)|nonce), a SINGLE pipe — see §4",
                "timestamp": "decorative, but must be non-empty; see the refusal case",
                "claim_response": "{'claim': [r, c], 'caught': bool} — the thief's honest "
                                  "answer to a capture claim",
                "win_claim": "{'type': 'survival'} on the thief's threshold turn",
            },
        },
        "audit_payload": {
            "required": ["sender", "records", "result_claim"],
            "field_notes": {
                "records": "the full sealed chain INCLUDING nonces, so the opponent re-hashes "
                           "every step with its own serializer",
                "result_claim": "what this side believes the sub-game ended as. The opponent's "
                                "audit settles it, never the claim.",
            },
        },
        "control_message": {
            "required": ["kind", "sender"],
            "optional": ["sub_game_number", "status", "step_budget", "payload"],
        },
        "validation": [
            {"message": m, "note": n, "verdict": ref.ref_turn_validate(m)} for m, n in cases
        ],
        "validate_before_applying": "every case above is decided BEFORE any state change. An "
                                    "inbound turn is adversarial input; a partially applied bad "
                                    "turn cannot be rolled back, and under App. E rule 35 a "
                                    "self-inflicted protocol fault zeroes BOTH teams.",
    })


def gen_pairing_declaration() -> None:
    """SPEC section 7.2 — the two pairing fields and their refusal truth table."""
    cases = [
        ({"sub_game_number": 3, "role": "thief"}, {"sub_game_number": 3, "role": "police"},
         "the ordinary case: same game, complementary sides"),
        ({"sub_game_number": 3, "role": "thief"}, {"sub_game_number": 5, "role": "police"},
         "sub-game mismatch -> refuse: one game cannot carry two indices, and a peer that runs "
         "ahead never resynchronises"),
        ({"sub_game_number": 3, "role": "police"}, {"sub_game_number": 3, "role": "police"},
         "role collision -> refuse: two of the same side can only deadlock"),
        ({"sub_game_number": 3, "role": "thief"}, {},
         "they declare nothing (the unmodified reference peer) -> play"),
        ({}, {"sub_game_number": 3, "role": "police"},
         "we declare nothing -> play; omission never refuses in either direction"),
        ({"sub_game_number": 3, "role": "thief"}, {"sub_game_number": "3", "role": "police"},
         "their sub-game is a string, not an int -> treated as silence, NOT as a mismatch: a "
         "cosmetic type difference must never cost a game"),
        ({"sub_game_number": 3, "role": "thief"}, {"sub_game_number": 3},
         "partial declaration -> the field they did declare is checked, the absent one is silence"),
    ]
    _write("pairing_declaration.json", {
        "description": "PROMOTED — the pairing declaration (SPEC section 7.2): sub_game_number "
                       "and role ride the negotiate extras BESIDE `terms`, never inside it (the "
                       "terms are a flat signed set; adding a key breaks the signature). "
                       "Identical terms give identical game_uids, so a mispairing is invisible by "
                       "the time an artifact exists — the handshake is the only place it can be "
                       "caught. Behaviour, not bytes, so it is pinned as a truth table. Promoted "
                       "2026-07-26: both fields were declared AND asserted by two independent "
                       "implementations across a full six-sub-game cross-team series on "
                       "2026-07-25 (imreeyal / anrbj666); the opponent's inbound greetings carry "
                       "both fields top-level, alternating correctly with the role swap.",
        "fields": {
            "sub_game_number": "the index of the sub-game THIS peer believes it is playing, taken "
                               "from its sealed step-0 record rather than re-read from a config "
                               "default (a re-read default is exactly what desynchronises)",
            "role": "'police' | 'thief' — the side this peer is playing in that sub-game",
            "placement": "top-level in the negotiate message, alongside nonce/signature/identity "
                         "and OUTSIDE `terms`",
        },
        "refusal_rule": [
            {"ours": o, "theirs": t, "note": n, "decision": ref.ref_pairing_decision(o, t)}
            for o, t, n in cases
        ],
        "why_it_compounds": "a failed handshake ends in about 60s while a real sub-game takes "
                            "minutes, so the side that failed runs AHEAD and never "
                            "resynchronises. Observed live: one side on sub-game 4 while the "
                            "other was still on sub-game 2 — two teams describing different "
                            "series, which is the shape App. E rule 35 zeroes for BOTH.",
    })


def gen_uid_declaration() -> None:
    """SPEC section 7.3 — declaring the derived game_uid at negotiate. PROPOSED."""
    terms = {
        "board_size": 7, "smell_grid_size": 5, "decay_per_step": 0.1, "emit_intensity": 0.9,
        "min_center_intensity": 0.5, "max_steps": 35, "barriers_max": 14, "setting": "Haifa",
        "hint_max_words": 15, "axis_origin_corner": "top-left", "axis_start_index": 0,
        "thief_start": [3, 3], "cop_start": [0, 0], "num_games": 6,
    }
    a, b = "team-aleph", "team-bet"
    right = ref.ref_game_uid(terms, a, b)
    # The wrong-input failure, reproduced exactly: the same deterministic derivation over a WIDER
    # object than the flat negotiated terms. Note it is a valid, stable uid — just not the one the
    # other side computes.
    wider = {**terms, "network": {"my_port": 8801}, "strategy": {"police_class": "example"}}
    wrong = ref.ref_game_uid(wider, a, b)
    cases = [
        (right, right, "both derived from the flat terms — the ordinary case"),
        (right, wrong, "their uid came from a WIDER config than the negotiated terms. It is "
                       "deterministic and self-consistent across all four of their artifacts, so "
                       "nothing on their side can see it — this row is the only place it surfaces "
                       "before the reports are diffed"),
        (right, None, "they declare nothing (the unmodified reference peer) -> play"),
        (None, right, "we declare nothing -> play; omission never refuses in either direction"),
        (None, None, "neither declares"),
        (right, 12345, "an uncomparable value is treated as silence, not as a mismatch"),
    ]
    _write("uid_declaration.json", {
        "description": "PROPOSED — declaring the derived game_uid at negotiate (SPEC section "
                       "7.3). The uid never crosses the wire: each peer derives it from the flat "
                       "negotiated terms and the two sorted group ids, so neither has anything to "
                       "compare against. A peer that derives it from the wrong input produces a "
                       "uid that is deterministic, self-consistent across its own four artifacts, "
                       "and wrong only against the opponent — invisible until two reports are "
                       "diffed, after the games are over. Observed live across a full six-sub-game "
                       "series on 2026-07-25. Behaviour, not bytes, so it is pinned as a truth "
                       "table. PROPOSED: both implementations have DECLARED it live since "
                       "2026-08-01 (every handshake through the 2026-08-04 counted series, both "
                       "role directions, values matching by independent derivation), but the "
                       "REFUSE row has never fired cross-team and only one implementation's "
                       "tests pin it — a behaviour table promotes on decisions, not on the "
                       "happy path. Finding credited to both "
                       "teams — imreeyal observed that the divergence was silent for the whole "
                       "series, anrbj666's root-cause analysis made the mechanism precise.",
        "field": {
            "name": "game_uid",
            "placement": "top-level in the negotiate message, beside `role` and "
                         "`sub_game_number` and OUTSIDE `terms` — the signed set is flat and "
                         "closed, so a key added there breaks the signature (section 4)",
            "value": "the uid this peer derived: "
                     "UUID(SHA256(canonical(flat_terms)|'|'.join(sorted([g_a,g_b])))[:16])",
        },
        "worked_example": {
            "note": "the same derivation over the right input and over a wider config; both are "
                    "valid stable uuids, which is precisely why the wrong one is hard to notice",
            "group_ids": [a, b],
            "flat_terms": terms,
            "wider_config": wider,
            "from_flat_terms": right,
            "from_a_wider_config": wrong,
            "identical": right == wrong,
        },
        "refusal_rule": [
            {"ours": o, "theirs": t, "note": n,
             "decision": ref.ref_uid_declaration_decision(o, t)}
            for o, t, n in cases
        ],
    })


def gen_smell_binding() -> None:
    """SPEC section 7.4 — `smell_binding:commit_grid_v1`, the owed vectors. PROPOSED.

    Three things are pinned, because three things can be got wrong independently: the digest
    over a populated grid (key ordering), the digest over the empty grid (`{}` is an input, not
    a gap), and the sealed record that carries the digest (the key must enter the section-3
    commit preimage, which is checkable only by showing that the commit MOVES when it is added).
    """
    grids = [
        (BINDING_SAMPLE_GRID,
         "a populated grid. The keys are STRINGS, so canonical JSON sorts them lexicographically "
         "and '10,1' precedes '2,3'. An implementation that sorts its grid numerically before "
         "serializing agrees with this fixture on every board narrower than eleven and silently "
         "disagrees on every board wider than ten"),
        ({}, "the empty grid — the `{}` convention. It is a legal input with a real digest, not "
             "an absence; a bound sender that transmits nothing seals THIS value and its audit "
             "passes. The binding is inert under a nothing-on-the-wire arrangement (the digest is "
             "constant) and still harmless"),
        (ref.ref_smell_emit([3, 3], 0.9, 5, 7),
         "the section-5 emitted field, bound as it would actually ride the wire — the digest is "
         "over the transmitted value, never over a re-derived or re-rounded copy"),
    ]
    # The sealed record: an ordinary section-3 move record, then the same record bound. The
    # commit construction does not change; what changes is the record it seals over.
    # The board is 12 wide on purpose: it is the only width at which the sample grid's `"10,1"`
    # key is a legal cell, and therefore the only width at which the lexicographic-ordering trap
    # this fixture pins can actually bite a real game.
    unbound_record = {
        "step": 4, "state": "grid=12x12;self=[2, 3];barriers=[]", "position": [2, 3],
        "move": "MOVE:E", "intent": "truth", "hint": "The alley smells of rain.",
    }
    nonce = "9f8e7d6c5b4a39281706f5e4d3c2b1a0"
    bound_record = ref.ref_bind_record(unbound_record, BINDING_SAMPLE_GRID)
    audit_cases = [
        (bound_record, BINDING_SAMPLE_GRID,
         "the ordinary case: the grid the verifier archived re-hashes to the digest the sender "
         "sealed"),
        (bound_record, {**BINDING_SAMPLE_GRID, "2,4": 0.5},
         "one cell differs between what was sealed and what was archived. Today this is at best "
         "evidence-grade in one team's dispute file; under the binding it is AUDIT-GRADE — the "
         "sender sealed one field and transmitted another"),
        (ref.ref_bind_record(unbound_record, {}), {},
         "a bound sender under a nothing-on-the-wire arrangement: `{}` sealed, `{}` archived, "
         "audit clean"),
        (bound_record, None,
         "a sender that claims a binding but transmitted no grid at all for the step. There is "
         "nothing that can re-hash to the digest, so it is a mismatch — and it is NOT the empty "
         "case above, which has a real digest of its own"),
        (unbound_record, BINDING_SAMPLE_GRID,
         "the peer never heard of the family and sealed no digest -> `unbound`, not a failure. "
         "The same rule as section 7's refusal table: silence is playable, in either direction"),
    ]
    _write("smell_binding.json", {
        "description": "PROPOSED — `smell_binding:commit_grid_v1` (SPEC section 7.4). Under the "
                       "reference wire the smell grid is the one per-step observable no "
                       "commitment covers, so a stale or forged frame is provable only to the "
                       "receiver that refused it. This binding seals "
                       "sha256(canonical_json(smell_grid_as_transmitted)) INSIDE the step record, "
                       "so the grid enters the existing commit preimage and a mismatch becomes "
                       "provable at the mutual audit. The wire is unchanged and the commit "
                       "algorithm is unchanged; only the sealed record grows a key. It buys "
                       "AUTHENTICITY and explicitly not privacy — an honest bound grid inverts to "
                       "the sender's cell exactly as an unbound one does. Proposed by anrbj666, "
                       "scoped by imreeyal, agreed 2026-07-29; no implementation has shipped it "
                       "yet, and because it changes a commit preimage it must never debut in a "
                       "counted game.",
        "digest": {
            "construction": "sha256(canonical_json(smell_grid_as_transmitted))",
            "vectors": [{"grid": g, "note": n, "sha256": ref.ref_smell_grid_sha256(g)}
                        for g, n in grids],
        },
        "sealed_record": {
            "note": "the binding key rides the section-3 preimage — same construction, larger "
                    "record. `commit_moves` is the point of this vector: if adding the key left "
                    "the commit unchanged, the grid would not be bound to anything. The board is "
                    "12 wide so that the sample grid's '10,1' key is a legal cell — the "
                    "lexicographic-ordering trap only bites on boards wider than ten.",
            "nonce": nonce,
            "grid": BINDING_SAMPLE_GRID,
            "unbound": {"record": unbound_record,
                        "commit": ref.ref_commit(unbound_record, nonce)},
            "bound": {"record": bound_record, "commit": ref.ref_commit(bound_record, nonce)},
            "commit_moves": ref.ref_commit(unbound_record, nonce) != ref.ref_commit(
                bound_record, nonce),
        },
        "audit_rule": [
            {"sealed_record": s, "archived_grid": g, "note": n,
             "verdict": ref.ref_binding_audit(s, g)}
            for s, g, n in audit_cases
        ],
        "declaration": {
            "note": "what crosses the wire is the family hash, exactly as for the other three "
                    "families (section 7) — the doc itself never does. Both registrations live "
                    "in locked_model.json; omission plays unbound.",
            "declared_key": "smell_binding_sha256",
            "registered": ["none", "commit_grid_v1"],
        },
    })


def gen_delivery_contract() -> None:
    """SPEC section 7.1 — the at-least-once receiver contract as a decision table."""
    played = {"1": "c1", "2": "c2"}
    state = {"played": played, "window": 2, "next": 3}
    arrivals = [
        ({"step": 3, "commit": "c3"}, "the next expected step"),
        ({"step": 2, "commit": "c2"}, "redelivery: SAME commit for a played step -> absorb, state "
                                      "unchanged. Dedupe on the commit, not on (kind, step)"),
        ({"step": 2, "commit": "cX"}, "a DIFFERENT commit for a played step -> equivocation. This "
                                      "is tampering evidence and must stay loud; a (kind, step) "
                                      "key would have collapsed it silently into the row above"),
        ({"step": 4, "commit": "c4"}, "one ahead, inside the reorder window -> buffer and replay "
                                      "in step order"),
        ({"step": 5, "commit": "c5"}, "at the window bound -> still buffered"),
        ({"step": 6, "commit": "c6"}, "past the window -> violation. Let the window BE the flood "
                                      "rule; a second threshold beside it is unreachable"),
        ({"step": 0, "commit": "c0"}, "below `next` and never played -> discard. `next` only "
                                      "advances past accepted steps, so this can never become "
                                      "applicable; buffering it holds it forever and two "
                                      "conformant receivers could diverge on it. NOTE: this row "
                                      "postdates the 2026-07-25/08-04 promotions and is not yet "
                                      "reproduced by a second implementation (anrbj666's audit, "
                                      "2026-08-04)"),
    ]
    zero_window = {"played": played, "window": 0, "next": 3}
    deadline_cases = [
        (100.0, 90.0, False, False, "quiet lap, in budget"),
        (100.0, 90.0, True, True, "tolerated traffic arrived -> the deadline does NOT move: one "
                                  "clock per EXPECTED message, so a stall burns the sender's "
                                  "budget, not ours"),
        (100.0, 100.0, True, True, "expires on a lap where a message DID arrive — a receiver that "
                                   "checks its clock only on an empty poll never checks it under "
                                   "a flood"),
    ]
    _write("delivery_contract.json", {
        "description": "PROMOTED — the at-least-once receiver contract (SPEC section 7.1). Both "
                       "registered wire shapes ride HTTP, which is at-least-once: a push whose "
                       "ack is lost is retried by a CORRECT client, so the same message arrives "
                       "twice by design, not only on bad networks. Behaviour, not bytes, so it is "
                       "pinned as a decision table. Promoted 2026-07-26: implemented "
                       "independently by two teams (2026-07-22) and then exercised across a full "
                       "six-sub-game cross-team series over public tunnels on 2026-07-25, mutual "
                       "audits clean both ways.",
        "state_shape": {
            "played": "{step: commit} — every step already applied, keyed by the commit that "
                      "sealed it",
            "window": "how many out-of-order steps may be buffered; 0 means none",
            "next": "the next step this receiver expects to apply",
        },
        "state": state,
        "arrivals": [
            {"arrival": a, "note": n, "decision": ref.ref_delivery_decision(state, a)}
            for a, n in arrivals
        ],
        "no_reorder_window": {
            "note": "the same one-ahead arrival against a receiver with window=0. A receiver with "
                    "no reorder window turns an ordinary retry race into a protocol violation — "
                    "under App. E rule 35 that is a self-inflicted technical loss zeroing BOTH "
                    "teams. Zero tolerance is not a tightening here.",
            "state": zero_window,
            "arrival": {"step": 4, "commit": "c4"},
            "decision": ref.ref_delivery_decision(zero_window, {"step": 4, "commit": "c4"}),
        },
        "deadline_rule": [
            {"deadline_at": d, "now": n, "arrived": a, "tolerated": t, "note": note,
             "decision": ref.ref_deadline_decision(d, n, a, t)}
            for d, n, a, t, note in deadline_cases
        ],
        "no_rules_tolerance": "none of this relaxes commit-reveal. Transport tolerance, no rules "
                              "tolerance: equivocation still collapses the game.",
    })


# --- book-v3 scent model (SPEC section 5.1; tier declared in TIERS) -----------------------


def _closed_form_probe() -> dict:
    """Evidence for why the kernel is pinned verbatim rather than as a formula."""
    peak, probes = 0.9, {"round": 1.3180, "trunc": 1.3440}
    out = {}
    for mode, sigma2 in probes.items():
        rows = []
        for i in range(5):
            row = []
            for j in range(5):
                d2 = (i - 2) ** 2 + (j - 2) ** 2
                v = peak * math.exp(-d2 / (2 * sigma2))
                row.append(round(v, 2) if mode == "round" else math.floor(v * 100) / 100)
            rows.append(row)
        out[mode] = {"sigma_squared": sigma2, "reproduces_printed_kernel": rows == BOOK_KERNEL_ROWS,
                     "quantized": rows}
    out["windows"] = {"round": [1.3178, 1.3327], "trunc": [1.3436, 1.3538]}
    out["note"] = (
        "Figure 4 IS an exact radial Gaussian at printed precision — but only inside a narrow "
        "sigma window the book never prints, and the window that works under round-to-2dp is "
        "DISJOINT from the one that works under truncation. A team deriving the kernel from its "
        "own fit lands outside the other team's window and gets a different field, silently. "
        "The printed 25 values are the only thing two implementations can both reach, so the "
        "kernel is pinned verbatim. (Reconciles the open question between our earlier reading — "
        "'the values match no clean formula' — and anrbj666's 'exact Gaussian': theirs is "
        "right about the shape, ours about the reproducibility. Both conclusions point here.)"
    )
    return out


def _ordering_probe() -> dict:
    """The model does no rounding, so algebraically-equal orderings are NOT byte-equal."""
    rho, cases = 0.1, []
    for tau, delta in ((0.05, 0.04), (0.05, 0.14), (0.1, 0.14)):
        pinned, alt = (1 - rho) * tau + delta, tau - rho * tau + delta
        cases.append({"tau": tau, "delta": delta, "pinned_order": pinned,
                      "alternative_order": alt, "equal": pinned == alt})
    return {
        "pinned": "(1 - rho) * tau + delta",
        "alternative": "tau - rho * tau + delta",
        "cases": cases,
        "note": "Algebraically identical, not identical in IEEE-754 doubles. Because this model "
                "rounds nothing and each side RECOMPUTES the rival's field rather than "
                "receiving it, a byte-comparison of two recomputed fields can differ on the "
                "last bit purely from evaluation order. Pin the order as written, or compare "
                "fields with a tolerance — do not do neither.",
    }


def gen_scent_book_v3() -> None:
    rho, center, board = 0.1, 0.9, 7
    emit = []
    for c, note in (([3, 3], "kernel deposited on an empty field, board centre"),
                    ([0, 0], "corner emission clipped to board bounds")):
        emit.append({"center": c, "note": note,
                     "field": ref.ref_book_full_turn({}, c, rho, center, board)})
    # Scalar traces: one cell's history, which is where the model's arithmetic is legible.
    pure = {"note": "book ch.4 worked example: a fresh centre trace after one full turn of "
                    "pure decay, no new deposit (the book prints ~0.81)",
            "tau": 0.9, "delta": 0.0, "after": ref.ref_book_update(0.9, 0.0, rho, center)}
    clamp = {"note": "the upper clamp earns its keep: the printed formula's max(0, .) alone "
                     "would leave 1.43, above the book's declared [0, 0.9] range for tau",
             "tau": 0.9, "delta": 0.62, "raw": (1 - rho) * 0.9 + 0.62,
             "after": ref.ref_book_update(0.9, 0.62, rho, center)}
    chain, tau = [], 0.0
    for delta in (0.62, 0.20, 0.20):
        tau = ref.ref_book_update(tau, delta, rho, center)
        chain.append({"delta": delta, "tau": tau})
    forked = ref.ref_book_update(chain[1]["tau"], 0.14, rho, center)
    scalar_chain = {
        "note": "three full turns of one cell, from an EMPTY start: an orthogonal deposit, then "
                "two turns at kernel distance 2. The fork shows the same predecessor under a "
                "0.14 deposit instead of 0.20. Values contributed by anrbj666 (Alon Engel, "
                "Renat Karimov) and re-derived here from the book's figure 4 alone.",
        "steps": chain, "fork_at_turn_3_with_delta_0_14": forked,
    }
    walk, field = [], {}
    for turn, pos in enumerate(([3, 3], [3, 4], [2, 4]), start=1):
        field = ref.ref_book_full_turn(field, pos, rho, center, board)
        walk.append({"turn": turn, "center": pos, "field": field})
    ref_field = ref.ref_smell_emit([3, 3], 0.9, 5, 7)
    book_field = ref.ref_book_full_turn({}, [3, 3], rho, center, board)
    _write("scent_book_v3.json", {
        "description": "PROMOTED — the book's ch.4 scent model as a named registration, "
                       "'multiplicative_book_v1', beside the reference's "
                       "'subtractive_chebyshev_v1' (section 5, CORE). Multiplicative decay "
                       "against a verbatim 5x5 figure-4 kernel, once per FULL turn, from an "
                       "empty start, with NO rounding. Promoted 2026-07-20 per the kit's own "
                       "bar: byte-exact clean-room reproduction by a second independent "
                       "implementation that predates these vectors (anrbj666, issue #6 — "
                       "kernel, 2/2 emits, 3/3 walk turns, both scalar traces, every "
                       "ordering-probe case with zero tolerance; their update natively "
                       "computes the pinned algebraic form). Spec facts contributed by "
                       "anrbj666 (Alon Engel, Renat Karimov); every value below is re-derived "
                       "here from book v3.0.0 ch.4 and App. F.",
        "model": _doc_scent_book(),
        "kernel": BOOK_KERNEL_ROWS,
        "closed_form_probe": _closed_form_probe(),
        "ordering_probe": _ordering_probe(),
        "emit": emit,
        "scalar_traces": {"pure_decay": pure, "clamp": clamp, "chain": scalar_chain},
        "field_walk": {
            "note": "three full turns of a moving agent's own trail on a 7x7 board, empty start",
            "board_size": board, "rho": rho, "center_intensity": center, "turns": walk,
        },
        "divergence_vs_reference": {
            "note": "one agent at [3,3] on an empty 7x7, after one turn, under each model — "
                    "the fields differ in shape AND support, so a team can see at a glance "
                    "which model it built. Neither is wrong; they are different registrations.",
            "center": [3, 3],
            "subtractive_chebyshev_v1": ref_field,
            "multiplicative_book_v1": book_field,
            "identical": ref_field == book_field,
        },
    })


# --- ENHANCEMENTS (opt-in, SPEC Appendix A) ----------------------------------------------

def gen_joint_seed() -> None:
    pairs = [("3f9a1c", "b27e04"), ("00", "ffffffffffffffff")]
    _write("joint_seed.json", {
        "description": "ENHANCEMENT (not required by the book): trustless coin flip for a shared "
                       "seed, if a pair opts into randomized starts instead of the book's fixed "
                       "configured starts. commit=SHA256(canonical({'seed_share':r})); "
                       "seed=SHA256(canonical({'shares':[r1,r2]})).",
        "vectors": [
            {"share_group_1": s1, "share_group_2": s2,
             "commit_group_1": ref.ref_share_commit(s1), "commit_group_2": ref.ref_share_commit(s2),
             "seed": ref.ref_joint_seed(s1, s2)}
            for s1, s2 in pairs
        ],
    })


def gen_derive_starts() -> None:
    cases = [("seed-alpha", 0, 7), ("seed-alpha", 1, 7), ("seed-beta", 0, 10), ("seed-beta", 16, 10)]
    vectors = []
    for seed, index, n in cases:
        cop, thief, draws = ref.ref_derive_starts(seed, index, n)
        vectors.append({"seed": seed, "index": index, "n": n, "cop": cop, "thief": thief, "draws": draws})
    _write("derive_starts.json", {
        "description": "ENHANCEMENT (not required by the book): seeded asymmetric starts, a "
                       "structural tie-breaker if a pair prefers randomized fair starts over the "
                       "book's fixed configured cop_start/thief_start. 4 digest bytes per cell, "
                       "minimum-Chebyshev deterministic re-draw, index = game*16 + attempt.",
        "vectors": vectors,
    })


def main() -> None:
    gen_canonical_json()
    gen_commit_reveal()
    gen_terms_signature()
    gen_game_uid()
    gen_pheromone()
    gen_report_consensus()
    gen_locked_model()
    gen_pairing_declaration()
    gen_uid_declaration()
    gen_smell_binding()
    gen_delivery_contract()
    gen_turn_message()
    gen_scent_book_v3()
    gen_joint_seed()
    gen_derive_starts()
    gen_index()


if __name__ == "__main__":
    main()
